### ISSUE TITLE
How to config ssl after get Let’s Encrypt certificate?

### ISSUE THREAD

**Issue by 7fantasysz** [atulmy/fullstack-javascript-architecture#13]
I use your template here to build my website. I am new to js and web-dev. It's really appreciated for your great work and save me time.
However, I tried a lot to configure my website into https but failed. What should I do and should not?
1. do I need to change the .env for backend/landing/web from http://example.com into https://example.com ?
2. should I mount certificate files into proxy container and configure in normal nginx ssl way?
3. no matter what I changed, trying to access my website of https://exmaple.com doesn't leave any logs in docker deployment_proxy_1. Doesn't this mean it is not working on https at all?
Really appreciate for your help. 
If you are interested in, we may also have conversation about a part-time role for our project here in Melbourne (Australia).

**Comment by atulmy** [comment]
Hi, glad you found the project helpful.

You should easily find tutorial on configuring SSL with Letsencrypt and nGinX. I recommend reading [this](https://www.humankode.com/ssl/how-to-set-up-free-ssl-certificates-from-lets-encrypt-using-docker-and-nginx) tutorial.

> 1. do I need to change the .env for backend/landing/web from http://example.com into https://example.com ?

Yes

> 2. should I mount certificate files into proxy container and configure in normal nginx ssl way?

Check the tutorial mentioned above.

> 3. no matter what I changed, trying to access my website of https://exmaple.com doesn't leave any logs in docker deployment_proxy_1. Doesn't this mean it is not working on https at all?
Really appreciate for your help.

Perhaps you have made an incorrect DNS settings or no DNS entries at all?

In case you are still finding it difficult to get the deployment done along with the right nGinX configuration, I'd suggest you to try out [DeployMonk](https://deploymonk.com/) and read the detailed docs [here](https://docs.deploymonk.com/guides-fullstack-javascript).

**Note**: [DeployMonk](https://deploymonk.com/) is a side project of mine. I created just for this recurring problem I faced of deploying projects.
