### ISSUE TITLE
ERROR: Service 'landing' failed to build : Build failed

### ISSUE THREAD

**Issue by randmaru** [atulmy/fullstack-javascript-architecture#16]
I don't know much about docker, but I get an error when building it. Maybe other developers will have it as well...
<details>
    <summary>Build log</summary>
    <pre>
PS C:\Users\randm\WebstormProjects\fullstack-javascript-architecture\deployment> docker-compose up --build -d
Building database
[+] Building 2.3s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 31B                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 34B                                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/mongo:latest                                                                                                                                            2.2s
 => CACHED [1/1] FROM docker.io/library/mongo@sha256:58ea1bc09f269a9b85b7e1fae83b7505952aaa521afaaca4131f558955743842                                                                                      0.0s
 => exporting to image                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                    0.0s
 => => writing image sha256:79c0ede5fa047e74c0b6f9d834f236511d01a41dc2347ef197c8661008c08a60                                                                                                               0.0s
 => => naming to docker.io/library/database                                                                                                                                                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building api
[+] Building 2.3s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 34B                                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/node:10                                                                                                                                                 2.2s
 => [internal] load build context                                                                                                                                                                          0.0s
 => => transferring context: 2.27kB                                                                                                                                                                        0.0s
 => [1/7] FROM docker.io/library/node:10@sha256:59531d2835edd5161c8f9512f9e095b1836f7a1fcb0ab73e005ec46047384911                                                                                           0.0s
 => CACHED [2/7] RUN mkdir -p /user/src/app                                                                                                                                                                0.0s
 => CACHED [3/7] WORKDIR /user/src/app                                                                                                                                                                     0.0s
 => CACHED [4/7] COPY ./package*.json ./                                                                                                                                                                   0.0s
 => CACHED [5/7] RUN npm install --quiet                                                                                                                                                                   0.0s
 => CACHED [6/7] COPY . ./                                                                                                                                                                                 0.0s
 => CACHED [7/7] RUN npm run build:prod                                                                                                                                                                    0.0s
 => exporting to image                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                    0.0s
 => => writing image sha256:b0e6ff0aca9c2af92bc699fb33e786144efa66cf8950e38917996348792f76ba                                                                                                               0.0s
 => => naming to docker.io/library/api                                                                                                                                                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Pulling proxy (nginx:)...
latest: Pulling from library/nginx
a330b6cecb98: Pull complete
e0ad2c0621bc: Pull complete
9e56c3e0e6b7: Pull complete
09f31c94adc6: Pull complete
32b26e9cdb83: Pull complete
20ab512bbb07: Pull complete
Digest: sha256:853b221d3341add7aaadf5f81dd088ea943ab9c918766e295321294b035f3f3e
Status: Downloaded newer image for nginx:latest
Building web
[+] Building 2.3s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 34B                                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/node:10                                                                                                                                                 2.2s
 => [1/8] FROM docker.io/library/node:10@sha256:59531d2835edd5161c8f9512f9e095b1836f7a1fcb0ab73e005ec46047384911                                                                                           0.0s
 => [internal] load build context                                                                                                                                                                          0.0s
 => => transferring context: 6.03kB                                                                                                                                                                        0.0s
 => CACHED [2/8] RUN mkdir -p /user/src/app                                                                                                                                                                0.0s
 => CACHED [3/8] WORKDIR /user/src/app                                                                                                                                                                     0.0s
 => CACHED [4/8] COPY ./package*.json ./                                                                                                                                                                   0.0s
 => CACHED [5/8] RUN npm install --quiet                                                                                                                                                                   0.0s
 => CACHED [6/8] RUN npm install -g serve                                                                                                                                                                  0.0s
 => CACHED [7/8] COPY . ./                                                                                                                                                                                 0.0s
 => CACHED [8/8] RUN npm run build                                                                                                                                                                         0.0s
 => exporting to image                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                    0.0s
 => => writing image sha256:23dd09a55107334f7f326ca5bf6ed38d3346c46343d7e0d0ceab6fd44328cf8a                                                                                                               0.0s
 => => naming to docker.io/library/web                                                                                                                                                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building landing
[+] Building 0.0s (1/2)
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                         0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount863442319/Dockerfile: no such file or directory
ERROR: Service 'landing' failed to build : Build failed
    </pre>
</details>

**Comment by atulmy** [comment]
Hello, this looks like a local docker issue rather than related to this repository. In case you face this issue, do open this again with additional logs.
